argumentcomputer/ci-workflows

.github/VERSION_CHECK.md
.github/workflows/rust-version-check.yml

feat: add a workflow that checks for rust version drift

---

.github/actions/gpu-setup/action.yml

When using OpenCL we are still compiling with CUDA, so this will cut down on compilation time as per https://github.com/filecoin-project/ec-gpu#environment-variables

fix: Always set `EC_GPU_CUDA_NVCC_ARGS`

---

.github/workflows/unused-deps.yml

- Updated the execution process for `cargo-udeps` in GitHub actions.
- Enhanced stability by using `RUSTC_BOOTSTRAP` variable in `unused-deps.yml`.
THis should help solve https://github.com/lurk-lab/arecibo/issues/247

ci: Improve stability of `cargo-udeps` in GitHub actions

---

.github/workflows/gpu-ci.yml

This should work with `lurk-rs`, `arecibo`, `neptune`, and `grumpkin-msm`. The last may need some tweaks once GPU CI lands in https://github.com/lurk-lab/grumpkin-msm/pull/9 or similar.

Improve `gpu-ci` workflow

---

.github/workflows/gpu-bench.yml
.github/workflows/gpu-ci.yml

- Modified GPU benchmarking and CI testing workflows in GitHub Actions.
- Removed `opencl` feature requirement in GPU benchmark workflow.
- Introduced an optional 'opencl' input parameter in the GPU CI Tests workflow.
- Made the execution of 'Rust tests on OpenCL' job conditionally dependent on the new 'opencl' input.

feat: Make OpenCL testing in GPU CI workflows optional

---

.github/workflows/rust-version-check.yml

Fixes #23 by using `rustup check` to get the latest Rust stable release.
- The `awk` script parses correctly with both an up-to-date local installation or an out-of-date one (the former was tested locally only). 
- Also enables an optional `patch` specifier e.g. in `1.70.0` rather than just `major.minor`
Successful run (expand the failing step to see the correct env values for `$RUST_VERSION` and `$TOOLCHAIN_VERSION`: https://github.com/lurk-lab/ci-lab/actions/runs/7535003798/job/20510418363

fix: `rust-version-check.yml`

---

.github/templates/VERSION_CHECK.md
.github/workflows/rust-version-check.yml

- Gets the local Rust version by running `rustup show` instead of the specifier in `rust-toolchain.toml`. If the latter doesn't specify a patch version (e.g. 1.72), it will update to the latest toolchain patch if it exists (e.g. 1.72.1). It thus seems more robust to parse `rustup show` directly, so we always have the fully-qualified version used by the crate. Then the comparison is simple because the output of `rustup check` will also always have the patch number.
- Adds some more info to the `VERSION_CHECK.md` issue template. I'm not sure whether the workflow file linked by the workflow run is that useful, but it's the most accurate file to show aside from a separate permalink.
Successful run:
https://github.com/lurk-lab/ci-lab/issues/62 …

fix: Improve version mismatch checks

---

.github/workflows/typos.yml

- Checks for typos using https://github.com/crate-ci/typos/
- Opens a PR with suggestions (from the `typos --write-changes` flag), and comments the errors it can't fix in the PR description
- Updates the same PR and description with new runs while it's open
- If errors are detected without actionable suggestions, no PR is opened. We could make it open an issue instead or wait till a solvable typo appears and both are visible in a PR.
- There doesn't seem to be a nice PR template we can use like https://github.com/JasonEtco/create-an-issue
- Requires some Git pathspec hackery to avoid committing the PR description `body-path` file
https://github.com/lurk-lab/ci-lab/pull/58 (see linked workflow run)

Add typo checker workflow

---

.github/workflows/bench-deploy.yml
.gitignore
Cargo.toml
build.rs
rust-toolchain.toml
src/json.rs
src/main.rs
src/plot.rs

This PR implements a `benchmark-plotter` crate, which turns Criterion benchmark JSON into historical plots deployed to `gh-pages`. It is comprised of the following:
- JSON deserializer in `src/json.rs` that extracts the plot-relevant data
- Plotting backend using https://github.com/plotters-rs/plotters
- Persistent `Plots` struct that saves historical results to disk for reuse
- `gh-pages` deployment action with some basic HTML to improve readability
- This is a PoC and should not be considered production-ready. There are several TODOs to address before using it in e.g. marketing material, chiefly visual improvements and incorporation into a SSG.
- The `plotters` configuration contains some hacks for visual clarity, so any usage downstream will likely need ad-hoc tweaks to the axes, …

Add benchmark plotting crate and workflow

---

.github/workflows/unused-deps.yml

https://github.com/lurk-lab/lurk-rs/issues/1102 gives a false positive by only running `--lib`, so it thinks deps used in `src/main.rs` are unused. By running against all packages and targets we fix this and check the full set of dependency usage in the caller crate.

fix: Run `cargo udeps` on all packages/targets

---

.github/workflows/bench-pr-comment.yml

- Re-introduces `!gpu-benchmark` as an alias for `!benchmark --features cuda`. This means that the default use case of "what does the perf look like for an average GPU run?" can now be simply run with `!gpu-benchmark`.
- Comments success or failure on the PR after the job completes, linking to the workflow run
- Fixes (hopefully) an issue where setting env vars between jobs caused the following error:
```
Error: Unable to process file command 'env' successfully.
Error: Invalid format '
'
```
This was likely due to `$GITHUB_OUTPUT` adding newlines when passed to the next job. Any newlines in an env var passed as a job output are now trimmed.
https://github.com/lurk-lab/ci-lab/pull/72#issuecomment-1959975697 and the following comments

Update `!benchmark` PR comment workflow

---

.github/actions/install-deps/action.yml
.github/workflows/lints.yml

Enables workflows to install prerequisite dependencies, which will allow us to fix [CI](https://github.com/lurk-lab/lurk-rs/actions/runs/8051573873/job/21989763496) for https://github.com/lurk-lab/lurk-rs/pull/1172
Successful run:
https://github.com/lurk-lab/ci-lab/actions/runs/8053253393/job/21995209009

Add `install-deps` action

---

.github/workflows/msrv.yml
.github/workflows/wasm.yml

Factors out the Wasm and MSRV checks from `lints.yml`, as we don't always want to run all three reusable workflows.

chore: Refactor lints

---

.github/workflows/bench-pr-comment.yml

Closes #50 by letting callers decide when to trigger the `issue_comment` workflow. For example, in a private repo the `author_association` check can be elided as permissions aren't as much of a concern.

Remove conditional in `bench-pr-comment.yml`

---

.github/workflows/codecov.yml

This enables Codecov to fail fast on a build error, such as https://github.com/lurk-lab/lurk-rs/actions/runs/8196615616/job/22417205470

fix: Build the workspace before running Codecov

---

.github/workflows/bench-pr-comment.yml

- Ensures the `cuda` feature is set by the `!gpu-benchmark` command
- Hopefully addresses https://github.com/lurk-lab/ci-workflows/issues/55 by enclosing the env var in quotes. Before, the script was running:
```
for var in '
'
```
which would likely cause the `Invalid format: '\n'` error
https://github.com/lurk-lab/ci-lab/pull/84
See [here](https://github.com/lurk-lab/ci-lab/actions/runs/8362068595/job/22891756312#step:12:63]) and [here](https://github.com/lurk-lab/ci-lab/actions/runs/8362068595/job/22891756312#step:12:128) for confirmation that the `cuda` feature is active.

fix: `cuda` feature and env in `bench-pr-comment.yml`

---

.github/workflows/bench-pr-comment.yml

Env vars are currently not being set properly as they are interpreted as one string literal rather than a list of strings. This leads to downstream issues such as https://github.com/lurk-lab/arecibo/pull/381#issuecomment-2079134046.
The values expand to multiple strings properly by removing quotes.
Successful runs: https://github.com/lurk-lab/ci-lab/pull/88

Fix `bench-pr-comment.yml` env

---

.github/actions/check-downstream-compiles/action.yml
.github/actions/ci-env/action.yml

- `check-downstream-compiles`: Recursively writes Git patches to all `Cargo.toml` files in the directory rather than only the top level, which ensures any nested workspaces are patched correctly. Any redundant patching of subcrates is a no-op that emits a safely ignorable compiler warning.
- `ci-env`: Sets the `env` vars properly, via `$GITHUB_ENV` rather than the job-level `env` keyword. Only the former actually persists after the composite action completes, as seen [here](https://github.com/wormhole-foundation/wp1/actions/runs/9166085252/job/25201708077?pr=218#step:7:5).
Successful run:
https://github.com/wormhole-foundation/wp1/actions/runs/9177178661/job/25234166925

fix: `ci-env` & `check-downstream-compiles` actions

---

.github/actions/check-downstream-compiles/action.yml

Optionally takes in the `more-paths` input, which will take the same Cargo.toml path patches for the initially patched crate and apply them to each specified crate further down the stack.
For example, https://github.com/lurk-lab/Plonky3/pull/6 shows:
- Plonky3 calls the downstream action and is the source of path patches
- Sphinx is the primary crate to be patched & checked, and saves its relevant patches to `patches.txt`
- Zk-light-clients is the secondary crate to be patched & check, which it does by simply writing the patches in `patches.txt` to each `Cargo.toml` file in the repo.
- More paths downstream of Sphinx could be specified, so long as they are checked out to a separate path in the caller repo.
> [!NOTE]
> This PR should be merged before …

feat: Support multiple crates in `check-downstream-compiles`

---

.github/actions/check-downstream-compiles/action.yml
crates/check-downstream-compiles/Cargo.toml
crates/check-downstream-compiles/src/main.rs

Fixes an issue where `[workspace.dependencies]` were being parsed incorrectly, as we only checked for `[dependencies]`.
Also adds a debug log for CI.
Successful run: https://github.com/argumentcomputer/sphinx/actions/runs/10359219500

fix: Workspace bug in `check-downstream-compiles`

---

.github/actions/tag-release/action.yml

Switches to commit mode in https://github.com/mikepenz/release-changelog-builder-action (see https://github.com/argumentcomputer/zk-light-clients/pull/268)

Switch to commit-mode for changelog
